config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'

  get 'contact' => 'static_pages#contact'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Wazito App", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About Us", about_path %></li>
				<li><%= link_to "Help", help_path %></li>				
				<li><%= link_to "Contact Us", contact_path %></li>				
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WazitoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>Andrew and Peter team. Wazito insiders!</p>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p>Get us on email and on phone.</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Need help? We offer help to all. Call Wazitos! </p>

app/views/static_pages/home.html.erb
<h1>Home Page</h1>
<p>Welcome to Wazito App.</p>
<%= link_to "Sign Up", users_new_path %>

app/views/users/new.html.erb
<h1 class="center">Sign Up</h1>
<div class="center">
	<%= form_for(@user) do |f|%>
		<%= f.label :name %> 
		<%= f.text_field :name %></br>

		<%= f.label :email %>
		<%= f.email_field :email %></br>

		<%= f.label :password %>
		<%= f.password_field :password%></br>

		<%= f.label :password_confirmation%>
		<%= f.password_field :password_confirmation%></br>

		<%= f.submit %>

	<% end %>	
</div>